== Setting up concrete5

=== Building the concrete5 JS and CSS assets

The concrete5 repository does not contain a working set of JavaScript and CSS files: you have to build them.
This is quite simple: open a command prompt and type the following commands
----
cd /D C:\Dev\Web\concrete5\5.7.git\build
npm install
grunt release
----
The `npm install` command downloads in a local folder the NodeJS libraries required to build the assets, and it must be just once (or if the `build/package.json` file changes).
`grunt release` is the command that effectively builds the JavaScripts and the CSSs needed by concrete5

=== Installing the PHP libraries for concrete5

concrete5 needs some third party PHP libraries.
Before being able to install concrete5 locally, you have to install them: open a command prompt and type these commands:
----
cd /D C:\Dev\Web\concrete5\5.7.git\web\concrete
composer install
----
Composer will start downloading all the required libraries (it may take a while and may require some user intervention - read what gets printed).
You'll have to call `composer install` every time that the file `web/concrete/composer.lock` changes.

At this point you have a fully working copy of concrete5: compliments!
